export const LOCALE_SET = 'LOCALE_SET';
export const LOCALE_GET = 'LOCALE_GET';
export const SET_SUBSCRIBE = 'SET_SUBSCRIBE';

export const GET_MOVIE_FETCH = 'GET_MOVIE_FETCH';
export const GET_MOVIE_RECEIVE = 'GET_MOVIE_RECEIVE';
export const GET_MOVIE_FAILURE = 'GET_MOVIE_FAILURE';

export const GET_MOVIE_LIST_FETCH = 'GET_MOVIE_LIST_FETCH';
export const GET_MOVIE_LIST_RECEIVE = 'GET_MOVIE_LIST_RECEIVE';
export const GET_MOVIE_LIST_FAILURE = 'GET_MOVIE_LIST_FAILURE';
